config/routes.rb
Rails.application.routes.draw do
  get 'splash/index'

  devise_for :users
  root 'splash#index'

  get '/user' => "categories#index", :as => :user_root

  resources :categories ,only: [:index, :show, :new, :create] do
    resources :payments, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_one_attached :icon
  has_and_belongs_to_many :payments

  validates :name, presence: true

  def value
    value = 0
    payments&.each do |payment|
      value += payment.amount
    end
    value
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :categories

  validates :name, presence: true
  validates :amount, presence: true

  validate :validate_category_presence

  private

  def validate_category_presence
    return unless categories.empty?

    errors.add(:categories, 'must be present')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories
  has_many :payments, foreign_key: 'author_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @categories = @user.categories
  end

  def show
    @user = current_user
    @category = @user.categories.find(params[:id])
    @payments = @category.payments.order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    @user = current_user
    @category = @user.categories.new(category_params)

    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @user = current_user
    @categories = @user.categories
    @category = @user.categories.find(params[:category_id])
    @payment = Payment.new
  end

  def create
    @user = current_user
    @payment = @user.payments.build(payment_params)
    @category = @user.categories.find(@payment.categories.first.id)

    if @payment.save
      redirect_to category_path(@category), notice: 'Payment was successfully created.'
    else
      @categories = @user.categories
      render :new
    end
  end

  private

  def payment_params
    params.require(:payment).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<div class='m-2 p-2 border d-flex justify-content-between bg-white' id="<%= dom_id category %>">
  <div class='d-flex gap-4 mx-2'>
    <% if category.present? %>
      <%= image_tag category.icon, :style => 'width: 64px; height: 64px; object-fit: cover;' %>
    <% end %>
    <div class='text-4 d-flex flex-column justify-content-between'>
      <%= category.name %>
      <br>
      <span class='small'><%= category.created_at.to_date %></span>
    </div>
  </div>
  <div class='m-2 d-flex align-items-center' >
    <strong class='text-center align-middle' ><%= number_to_currency(category.value, precision: 2) %></strong>
  </div>
</div>

app/views/categories/index.html.erb
<div class="nav bg--primary d-flex justify-content-between align-items-center p-2 fixed-top">
  <%= button_to destroy_user_session_path, method: :delete, class: 'bg-transparent text-white m-0 border-0 text-decoration-none' do %>
    <i class="bi bi-arrow-left"></i> Log out
  <% end %>
  <h5 class='text-white m-0 py-2 text-uppercase font-weight-bold'>Categories</h5>
  <%= button_to request.referrer, method: :get, class: 'bg-transparent text-white m-0 border-0 text-decoration-none' do %>
    <i class="bi bi-search"></i>
  <% end %>
</div>
<div class="mb-6 mt-6">
  <% @categories.each do |category| %>
    <%= link_to(category_path(category), class: "text-decoration-none link-dark") do%>
      <%= render category %>
    <% end %>
  <% end %>
</div>
<div class="bg-second d-flex justify-content-center fixed-bottom">
  <div class="custom-btn__wrapper custom-btn__wrapper--secondary">
    <%= button_to "NEW CATEGORY", new_category_path, method: :get, class: 'custom-btn custom-btn--secondary' %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="nav bg--primary d-flex justify-content-between align-items-center p-2  fixed-top">
  <%= button_to categories_path, method: :get, class: 'bg-transparent text-white m-0 border-0 text-decoration-none' do %>
    <i class="bi bi-arrow-left"></i>
  <% end %>
  <h5 class='text-white m-0 py-2 text-uppercase font-weight-bold'>New Category</h5>
  <%= button_to  root_path, method: :get, class: 'bg-transparent text-white m-0 border-0 text-decoration-none' do %>
    <i class="bi bi-house-door-fill"></i>
  <% end %>
</div>
<%= form_with(model: @category,  html: { class: "mt-6 mx-2 d-flex flex-column gap-1" }) do |form| %>
  <div class="p-2 bg-white">
    <%= form.file_field :icon, class: 'form-control file-input rounded-0 border-0' , id: 'icon-input' %>
  </div>
  <div class="p-2 bg-white">
    <%= form.text_field :name, class: 'form-control rounded-0 border-0', placeholder: "#{:name}".capitalize %>
    <% if @category.errors.has_key?(:name) %>
      <p class="text-danger"><%= @category.errors[:name].join(', ') %></p>
    <% end %>
  </div>
  <% if @category.errors.any? %>
    <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="custom-btn__wrapper custom-btn__wrapper--secondary fixed-bottom">
    <%= form.submit class:"custom-btn custom-btn--secondary" %>
  </div>
<% end %>

app/views/categories/show.html.erb
<div class="nav bg--primary d-flex justify-content-between align-items-center p-2 fixed-top">
  <%= button_to categories_path, method: :get, class: 'bg-transparent text-white m-0 border-0 text-decoration-none' do %>
    <i class="bi bi-list"></i>
  <% end %>
  <h5 class='text-white m-0 py-2 text-uppercase font-weight-bold'><%= @category.name %></h5>
  <%= button_to request.referrer, method: :get, class: 'bg-transparent text-white m-0 border-0 text-decoration-none' do %>
    <i class="bi bi-search"></i>
  <% end %>
</div>
<div class="d-flex justify-content-between bg-white p-4 border-2 border-bottom mt-5">
  <span class="gray--dark">Payment Credit</span>
  <span class="font--bold gray--dark"><%= number_to_currency(@category.value, precision: 2) %></span>
</div>
<div class="mb-6">
  <% @payments.each do |payment| %>
    <%= render payment %>
  <% end %>
</div>
<div class="bg-second d-flex justify-content-center fixed-bottom">
  <div class="custom-btn__wrapper custom-btn__wrapper--secondary">
    <%= button_to "NEW Payment", new_category_payment_path(@category), method: :get, class: 'custom-btn custom-btn--secondary text-uppercase' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnapPay</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body class="snap-container">
    <%= yield %>
  </body>
</html>

app/views/payments/_payment.html.erb
<div class='m-2 p-2 border d-flex justify-content-between bg-white' id="<%= dom_id payment %>">
  <div class='d-flex gap-4 mx-2'>
    <div class='d-flex flex-column justify-content-between gray'>
      <h6 ><%= payment.name %></h6>
      <span class='small'><%= payment.created_at.to_date %></span>
    </div>
  </div>
  <div class='m-2 d-flex align-items-center' >
    <strong class='text-center align-middle font--bold gray--dark' ><%= number_to_currency(payment.amount, precision: 2) %></strong>
  </div>
</div>

app/views/payments/new.html.erb
<div class="nav bg--primary d-flex justify-content-between align-items-center p-2  fixed-top">
  <%= button_to category_path(@category), method: :get, class: 'bg-transparent text-white m-0 border-0 text-decoration-none' do %>
    <i class="bi bi-arrow-left"></i>
  <% end %>
  <h5 class='text-white m-0 py-2 text-uppercase font-weight-bold'>New Payment</h5>
  <%= button_to request.referrer, method: :get, class: 'bg-transparent text-white m-0 border-0 text-decoration-none' do %>
    <i class="bi bi-search"></i>
  <% end %>
</div>
<%= form_with(model: @payment,url: category_payments_path, local: true, html: { class: "mt-6 mx-2 d-flex flex-column gap-1" }) do |form| %>
  <div class="p-2 bg-white">
    <%= form.text_field :name, class: 'form-control rounded-0 border-0', placeholder: "#{:name}".capitalize %>
    <% if @payment.errors.has_key?(:name) %>
      <p class="text-danger"><%= @payment.errors[:name].join(', ') %></p>
    <% end %>
  </div>
  <div class="p-2 bg-white">
    <%= form.text_field :amount, class: 'form-control rounded-0 border-0', placeholder: "#{:amount}".capitalize %>
    <% if @payment.errors[:amount].any? %>
      <div class="text-danger">
        <%= @payment.errors[:amount].join(", ") %>
      </div>
    <% end %>
  </div>
  <div class="p-2 bg-white">
    <%= form.label :category_ids, 'Categories' , class:"mb-2" %>
    <br>
    <%= form.collection_check_boxes(:category_ids, @categories, :id, :name) do |category| %>
      <div class="form-check">
        <%= category.check_box(class: "form-check-input", id: dom_id(category.object)) %>
        <%= category.label(class: "form-check-label", for: dom_id(category.object)) do %>
          <%= category.text %>
        <% end %>
      </div>
    <% end %>
    <% if @payment.errors[:category_ids].any? %>
      <div class="text-danger">
        <%= @payment.errors[:category_ids].join(", ") %>
      </div>
    <% end %>
  </div>
</div>
<div class="custom-btn__wrapper custom-btn__wrapper--secondary fixed-bottom">
  <%= form.submit class: 'custom-btn custom-btn--secondary' %>
</div>
<% end %>

app/views/splash/index.html.erb
<div class='vh-100 d-flex flex-column align-items-center justify-content-center'>
  <div class="h-50 w-100 p-4 d-flex flex-column align-items-center justify-content-between">
    <%= image_tag("logo.svg", alt: "Snap Scan Logo") %>
    <div class="d-flex flex-column gx-3 w-100 fixed-bottom px-2 pb-2">
      <%= button_to 'Log in', new_user_session_path, method: :get, class: 'p-2 w-100 my-2 text-white custom-btn--primary border-0' %>
      <%= button_to 'Sign up', new_user_registration_path, method: :get, class: 'border-0 w-100' %>
    </div>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>